### ISSUE TITLE
Error when handling column names which use reserved keywords

### ISSUE THREAD

**Issue by beatbull** [EXASOL/spark-exasol-connector#1]
Thanks for working on a spark connector for Exasol. It works well so far. Though I stumbled on an issue regarding reserved keywords. If the query is returning a column, which is a reserved keyword in Exasol (e.g. "CONDITION" in the example below), I get following stacktrace:
```
Caused by: java.sql.SQLException: syntax error, unexpected CONDITION_ [line 1, column 61] (Session: 1611504535207481827)
	at com.exasol.jdbc.ExceptionFactory.createSQLException(ExceptionFactory.java:175)
	at com.exasol.jdbc.EXASQLException.getSQLExceptionIntern(EXASQLException.java:50)
	at com.exasol.jdbc.AbstractEXAStatement.execute(AbstractEXAStatement.java:468)
	at com.exasol.jdbc.EXAStatement.execute(EXAStatement.java:278)
	at com.exasol.jdbc.AbstractEXAStatement.executeQuery(AbstractEXAStatement.java:601)
	at com.exasol.spark.rdd.ExasolRDD.compute(ExasolRDD.scala:123)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
...
```
In the query it doesn't matter whether the column is referenced via `"CONDITION"` (proper escaping via quotes) or with the table alias, e.g. `products.condition` - it results in the same error.

I don't see this error when using JDBC for the same query (we've been using the same query for more than a year via JDBC). The error only shows up when using the spark-exasol-connector. Which is strange, as reading the stacktrace the error comes from the JDBC driver. Probably the JDBC driver has some special handling for such column names (?)

However, there's a simple workaround for this issue by renaming the respective column in the query, e.g. `"CONDITION" AS product_condition`. Then the error disappears and I get the result. The column can be renamed later in the data frame.

**Comment by morazow** [comment]
Hello @beatbull ,

Thanks for reporting this! Please keep providing your feedback!

I am going to add this as todo for time being. The connector does not obey the quoting yet; they are put as plain Scala strings when doing column-pruning.

```scala
private[this] def enrichQuery(columns: Array[String], filters: Array[Filter]): String = {
    val columnStr = if (columns.isEmpty) "*" else columns.mkString(", ")
    s"SELECT $columnStr FROM ($queryString)"
}
```

However, I am going to look into it in the coming weeks.

**Comment by beatbull** [comment]
Hello @morazow ,

thanks for the quick response. Indeed the snippet you posted is causing the issue with the reserved keywords - qouting the columns or prefixing them with a table alias (e.g. `columns.map(col => s"a.$col").mkString(", ")` in combination with a table alias in the query) would fix the issue easily.

**Comment by beatbull** [comment]
I could also push a PR but seems I lack permissions to do so.

**Comment by morazow** [comment]
Hello @beatbull,

Thanks for the proposal! The pull requests are very much welcome!

I will check and ask to update the permissions if people cannot send a pull request.

Meanwhile, I have pushed a [branch](https://github.com/EXASOL/spark-exasol-connector/tree/task/column-quotes) with your proposal of adding a prefix to selected columns.

Please let me know if that solves your issue.

**Comment by beatbull** [comment]
Hi @morazow ,

I tried the suggested fix, it works fine when using reserved keywords as column names in queries. Thanks for the quick fix.

**Comment by morazow** [comment]
Hey @beatbull ,
Great to hear it works! Please let us know if there are any issues!

I am going to close this issue and merge other branches to master.
