### ISSUE TITLE
java.sql.SQLException: Cannot handle data type: 2005

### ISSUE THREAD

**Issue by sameh-sharaf** [exasol/spark-exasol-connector#100]
Hi,

We are using `spark-exasol-connector` to import our processed data from Databricks to Exasol. We are facing an issue when importing columns of type `string` in Databricks with values `NULL` with the error `java.sql.SQLException: Cannot handle data type: 2005`.

Exasol target table uses `VARCHAR2`.

Our Databricks cluster uses `com.exasol:spark-connector_2.12:1.1.0` and `com.exasol:exasol-jdbc:6.1.7`.

Could you advise on this please?

Thank you,
Sameh

**Comment by morazow** [comment]
Hello @sameh-sharaf,

Thanks for the feedback!

Could you please share more of the exception stack trace if possible?

One thing you could do is to convert `null` values to empty strings before saving to Exasol. Exasol stores them as empty strings.

```
df.na.fill("").write...
```

Do you also put size to the column, `VARCHAR2(n)`? Where `n` is expected maximum length.

**Comment by sameh-sharaf** [comment]
Hi @morazow 

Thank you for getting back.

Actually, we currently use empty strings instead of `null` values to workaround this issue. We do specify `VARCHAR2` length (`VARCHAR2(n)`) when defining our schemas.

Here is the full exception returned:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 8, 10.152.220.213, executor 1): java.sql.SQLException: Cannot handle data type: 2005
```
Here is a code sample which reproduces the error:
```
pydf = spark.sql("""select 1 as col1, cast(null as string) as col2
union all
select 2, cast('test' as string)""")
pydf.registerTempTable('EB_TBL1_20211028')

jdbcDriver = 'com.exasol.jdbc.EXADriver'
dbURL = 'jdbc:exa:0.0.0.0'
dbUser = '<username>'
dbPassword = '<password>'

spark.sql("select * from EB_TEST_20211028 ").write.format('jdbc').options(
    url=dbURL,
    driver=jdbcDriver,
    dbtable="<schema>.EB_TEST_20211028",
    user=dbUser,
    password=dbPassword).option("numPartitions",1).option("encryption", "0").mode("append").save()
```

We currently updated `exasol-jdbc` to `7.1.2` for testing. Therefore, we used the option `encryption=0` to disable TLS handshake issues.

**Comment by morazow** [comment]
Hello @sameh-sharaf,

> we currently use empty strings instead of null values to workaround this issue

That is a valid solution for this issue.

The issue happens because `NULL` values in the Spark dataframe are transferred as `CLOB` data type via JDBC which causes an unsupported data type error.

Another option is to replace `null` values with empty strings just before writing to Exasol (as mentioned above) with `df.na.fill("").write.format....`.

**Comment by sameh-sharaf** [comment]
Hi @morazow 

Thank you for your feedback. Looks like we'll stick to the workaround for now.

**Comment by morazow** [comment]
Hello @sameh-sharaf,

Thanks for the feedback! We are going to close the ticket for now. Please let us know if there are any issues.
