### ISSUE TITLE
Column order is mixed up in Exasol selects due to internal query wrapping

### ISSUE THREAD

**Issue by beatbull** [exasol/spark-exasol-connector#35]
Thanks for continuously improving the spark-exasol-connector. It really simplifies leveraging Exasol data in spark.

I've upgraded to the latest available release 0.1.3 of the spark-exasol-connector. I tried reading data from Exasol and writing to Spark using `insertInto`. `insertInto` ignores column names and relies on column order (see https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.DataFrameWriter). So my expected behavior was that if I define the exact same order of column in my Exasol query as used in the target Hive table, everything should work fine. Unfortunately, an internal query-wrapping step in the spark-exasol-connector mixes up the column order.

I've spotted the issue in the code in https://github.com/exasol/spark-exasol-connector/blob/master/src/main/scala/com/exasol/spark/ExasolRelation.scala#L108 , though I haven't investigated further where the mixed up columns originate from. It would be great if the query-wrapper in ExasolRelation would keep the same column order as the original query.

Thanks.

**Comment by morazow** [comment]
Hello @beatbull,

Thanks for opening this issue!

Could you please clarify, when you say `insertInto` is it Spark SQL syntax?

For example,
```scala
exaDF.createGlobalTempView("exaTable")
val res = spark.sql("INSERT INTO TABLE myTable SELECT * FROM exaTable")
res.show(10)
```

If you have an example, could you please provide it?

As you probably know, we do not have saving into Exasol feature yet. (I am working on this on my fork). However, if it "INSERT INTO" syntax, it might be easier to provide that with [`InsertableRelation`](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.sources.InsertableRelation) on ExasolRelation.

**Comment by beatbull** [comment]
I'm reading from Exasol via spark-exasol-connector and write to a Hive table using Spark's `insertInto`. So I'm not inserting to Exasol via spark, only reading from it.

**Comment by beatbull** [comment]
Hi @morazow ,

the problem seems to be a bit more relevant. I tried using `saveAsTable` to store the data retrieved from Exasol via the spark-exasol-connector into a Hive table. Unfortunately, this doesn't work in spark due to https://community.hortonworks.com/content/supportkb/210572/how-to-append-data-to-an-hive-orc-table-from-spark.html . So I have to use `insertInto` when writing the DataFrame to the target Hive table. Since the spark-exasol-connector is mixing the column order up, I have to add an additional step to assure the order of columns in the DataFrame are exactly the same as the target Hive table.

```scala
val columns = df.sparkSession.catalog.listColumns(targetTable)
df
  .select(columns.collect.map(column => col(column.name)).toList: _*)
  .write
  .mode(SaveMode.Append)
  .insertInto(targetTable)
```

If the spark-exasol-connector would keep the column order as it was defined in the SQL query, the additional `select` for reordering the columns would not be necessary.

**Comment by morazow** [comment]
Hello @beatbull,

I have finally found time to look into this issue. 

However, I have not been able to pinpoint the problem to column ordering in connector side.

Could you please compare the schema-s from both dataframe and hive table?

E.g.

```scala
exaDF.printSchema()

sparkSession.table("dbName.tableName").printSchema()
```

I created short hive example to test the issue, you can check it here, https://gist.github.com/morazow/3580d6c4c7a2ee46362949a4efdc6aee. I used Spark 2.4.0 and AWS EMR 5.20.0 and running Exasol 6.0.13 database.

One thing I noticed that Spark tries to infer the Hive table schema first from underlying files (if for instance they are stored as parquet), if it cannot infer, then uses the Hive metastore information to get a table schema.

In general above `printSchema` should be same for both. Please also check that you are not getting `cast` exceptions, for instance, decimal to date.

**Comment by beatbull** [comment]
Hello @morazow , 

thank you for checking this issue and providing an example. Unfortunately, the example query uses too few columns in the select and it looks like you simply got lucky. I took your example and changed the query, adding a few more columns:

```sql
SELECT MARKET_ID, SALES_DATE, PRICE, TERMINAL_ID, EXTRACT(YEAR FROM SALES_DATE) AS THE_YEAR, SALES_ID
      FROM RETAIL.SALES
      WHERE MARKET_ID IN (661, 534, 667)
```

Also I added a `df.show()` before `df.printSchema()`. With more columns, the mixup effect shows up, it is easy to see in the log message:

```
INFO  ExasolRelation:109 - Running with enriched query: SELECT A.SALES_DATE, A.PRICE, A.MARKET_ID, A.THE_YEAR, A.SALES_ID, A.TERMINAL_ID FROM (
      SELECT MARKET_ID, SALES_DATE, PRICE, TERMINAL_ID, EXTRACT(YEAR FROM SALES_DATE) AS THE_YEAR, SALES_ID
      FROM RETAIL.SALES
      WHERE MARKET_ID IN (661, 534, 667)
    ) A 
```

The column order is mixed up due to an internal query wrapping within the spark-exasol-connector.

**Comment by morazow** [comment]
Good morning @beatbull,

It is great that you have pointed a problematic query. Let me have another look using your example query.

**Comment by morazow** [comment]
Hello @beatbull,

I have added some more logs (on my fork) to check what was going, you can check them [here](https://github.com/morazow/spark-exasol-connector/commit/2df6467dfdb658d5da4ceb3e80ce44418ce45e12).

Indeed the columns are reordered. However, it is what Spark provides with `requiredColumns` inside `buildScan(columns, filters)` function. I could not understand, why regular without parameters `buildScan()` function is not called here.

**However**, I was able to write into Hive table correctly despite that columns are reordered when reading. So if there is no `select` Spark rearranges them back based on schema?

I think I cannot do anything from connector side. Rearranging columns would not be feasible because of  dataframe `select` operations providing requiredColumns.

Since writing to Hive is positional (not based on column names), it is better you perform select on dataframe before writing.

---

Hive Table:
```sql
DROP TABLE IF EXISTS HIVE_SALES;

CREATE TABLE HIVE_SALES (
  MARKET_ID               INT,
  SALES_DATE              DATE,
  PRICE                   DOUBLE,
  TERMINAL_ID             INT,
  THE_YEAR                INT,
  SALES_ID                INT
)
STORED AS PARQUET
TBLPROPERTIES ("parquet.compression"="SNAPPY");
```

Results:
```sh
$ hive -e "select market_id, sales_date, price, terminal_id, the_year, sales_id from default.hive_sales"

Logging initialized using configuration in file:/etc/hive/conf.dist/hive-log4j2.properties Async: false
OK
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
667     2017-12-31      10.0    1337    2017    1
534     2017-12-30      7.0     1234    2017    4
534     2017-12-30      11.0    1235    2017    5
661     2017-12-30      30.0    123     2017    3
661     2017-12-31      32.0    124     2017    6
Time taken: 2.589 seconds, Fetched: 5 row(s)
```

**Comment by beatbull** [comment]
Hello @morazow ,

thanks for further investigating the issue. For me the column order was messed up (in an even bigger query with more columns) which resulted in data type mismatch errors.

Ok, so then I'll keep my "workaround" for now (posted in the first message in this issue) which reorders columns in the data frame to make absolutely sure the positions are correct.

Thanks.

**Comment by morazow** [comment]
I am going to close this now. Let us discuss again when we found out more about this in general.
