### ISSUE TITLE
Cross compile with Scala 2.12+

### ISSUE THREAD

**Issue by morazow** [exasol/spark-exasol-connector#38]
Since most recent Spark version (2.4+) was moved to Scala 2.12+ (finally), we should also be able to compile with Scala version 2.12+.

Currently, we depend on [Spark Testing Base](https://github.com/holdenk/spark-testing-base/pull/275) library, once it is merged we can also start working on it.

Some resources to read on the migration efforts:
- [SPARK-14220](https://issues.apache.org/jira/browse/SPARK-14220)
- [Spark as a Scala gateway drug and the Scala 2.12 failure](https://contributors.scala-lang.org/t/spark-as-a-scala-gateway-drug-and-the-2-12-failure/1747/20)
- [How Lightbend got Apache Spark to Work with Scala 2.12](https://www.lightbend.com/blog/how-lightbend-got-apache-spark-to-work-with-scala-2-12)

**Comment by dbast** [comment]
spark-testing-base 2.4.3_0.12.0 is available :)

**Comment by morazow** [comment]
Thanks @dbast, that is great news!

I am going to check the version updates soon. There might be some issues with sbt plugins on Scala 2.12.
