### ISSUE TITLE
Expand test environment

### ISSUE THREAD

**Issue by jpizagno** [exasol/spark-exasol-connector#40]
We would like to test in cluster environment. The cluster environment could include both Exasol and Spark clusters.  This could be done using docker-compose (Exasol Cluster and Spark-master and Spark-Workers).

Further details can be discussed in the ticket.

**Comment by redcatbear** [comment]
@morazow: During board check I just saw that this ticket has both a feature and a refactoring label. Please split into two individual tickets.

**Comment by morazow** [comment]
Good catch! 
Since this mostly about improving the test setup, I have removed the feature label.

**Comment by morazow** [comment]
Another acceptance criteria:

- Remove the manual docker network creation (review suggestion from #82)
