### ISSUE TITLE
Pyspark example

### ISSUE THREAD

**Issue by mabdelrazzak** [exasol/spark-exasol-connector#41]
Hi,
Can you please provide a sample code for using it in pyspark? I'm trying to write a dataframe into an Exasol table, I'm currently using JDBC but it does not allow me to create the table if not exist.

df.write \
            .format("jdbc") \
            .option("driver", "com.exasol.jdbc.EXADriver") \
            .option("url", URL) \
            .option("dbtable", "mytable") \
            .option("user", "myuser") \
            .option("password", "mypass") \
            .option("useSSL", "false") \
            .mode('overwrite') \
            .save()

**Comment by jpizagno** [comment]
@mabdelrazzak 
You may need to include the option : .option("create_table","true")

Also you need Spark Version 2.1+.

Try this example and get back to us:

```shell
shell% git clone https://github.com/exasol/spark-exasol-connector.git
shell% cd spark-exasol-connector
shell% ./sbtx assembly
shell% pyspark --master yarn --deploy-mode client --jars ./target/scala-2.11/spark-exasol-connector-assembly-0.2.0.jar --num-executors=32
...
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.2.1
      /_/

....
>>> from pyspark.sql import *
>>> Employee = Row("firstName", "lastName", "email", "salary")
>>> employee1 = Employee("john","doe","jdoe@github.com",100000)
>>> employee2 = Employee("mary","smith","msmith@github.com",120000)
>>> employees = [employee1 , employee2]
>>> employees_dataframe = spark.createDataFrame(employees)
>>> exasol_host = "10.29.7.11"
>>> exasol_port = "8563"
>>> exasol_password = "12345"
>>> exasol_user = "jim"
>>> employees_dataframe.write.mode("overwrite").option("host",exasol_host).option("port",exasol_port).option("username",exasol_user).option("password",exasol_password).option("table","OV_AS_ACCESS_LAB.EMPLOYEE").option("create_table","true").format("exasol").save()

>>>      
```

and then in ExaPlus GUI I see
```sql
SELECT *
FROM OV_AS_ACCESS_LAB.EMPLOYEE
;

FIRSTNAME	LASTNAME	EMAIL	SALARY
john	doe	jdoe@github.com	100000
mary	smith	msmith@github.com	120000
```

**Comment by morazow** [comment]
Hello @mabdelrazzak,

Yes, you can use the setup and example provided above by @jpizagno.

Similarly, if you want to skip assembling the jar, you can use these two lines with `pyspark` command:
```
--repositories https://maven.exasol.com/artifactory/exasol-releases \
--packages com.exasol:spark-connector_2.11:0.2.0
```

I have written short walkthrough example, it is mostly for Scala but should work with PySpark also. Please find it [here](https://github.com/exasol/spark-exasol-connector/blob/master/docs/example-walkthrough.md).

In you code example, you are using the general JDBC connector which is built in into Spark. However, we cannot support you very much there. Give a try to this Spark Exasol connector, where we are happy to support you!

Please do not hesitate to let us know if you have any other questions or feedback!

**Comment by mabdelrazzak** [comment]
Hello,

Thanks for your feedback(s).
**I have followed the first example: @jpizagno** 

employees_dataframe.write \
...         .format("exasol") \
...         .option("host", "myserver") \
...         .option("table", "Test_TBL") \
...         .option("port", "8563") \
...         .option("username", "myuser") \
...         .option("password", "mypassword") \
...         .option("useSSL", "false") \
...         .option("create_table", "true") \
...         .mode('append') \
...         .save()

And it gave me the below error:
com.exasol.jdbc.ConnectFailed: connect timed out

And when I'm using PyCharm, I get the following:
java.lang.ClassNotFoundException: Failed to find data source: exasol.

In Pycharm, it uses the following command to run my script:
/usr/local/bin/python3.7 /Users/myuser/PycharmProjects/MyProject/Test_Spark_LoadToExasol_withExasol_connctor.py --master yarn --deploy-mode client --jars /usr/local/lib/python3.7/site-packages/spark-exasol-connector/target/scala-2.11/spark-exasol-connector-assembly-0.2.0.jar --num-executors=32


**I have tried solution # 2 @morazow** 
I got the below exception:

Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/usr/local/Cellar/apache-spark/2.4.0/libexec/python/pyspark/sql/readwriter.py", line 734, in save
    self._jwrite.save()
  File "/usr/local/Cellar/apache-spark/2.4.0/libexec/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/Cellar/apache-spark/2.4.0/libexec/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/local/Cellar/apache-spark/2.4.0/libexec/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o57.save.
: java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/RelationProvider

**Comment by morazow** [comment]
Hey @mabdelrazzak,

Thanks for trying out different approaches! 

I think we are more close to getting it working on the first error :) On other cases it seems like the dependent libraries of connector are not loaded.

Could you please check that you can connect on [ports in range [20000..21000]](https://www.exasol.com/portal/display/DOC/Default+Ports) to Exasol database?

The connector uses Exasol [sub-connections](https://www.exasol.com/support/browse/SOL-546) which return a sub connection url and port in above range that each Spark tasks needs to connect.

**Comment by jpizagno** [comment]
@mabdelrazzak 
     Thanks for trying our solutions. Just to explain my suggestion, the parameter "--num-executors=32" may be important.  If I do not use the correct number, then I also get connection problems.  

How many nodes are in your Exasol Cluster ?
(this is related to @morazow 's answer)

There is not a 1-1 mapping, but the number of Spark executors may need to be greater (or equal to) the number of Exasol Nodes.

Maybe @morazow can elaborate.

thanks again

**Comment by mabdelrazzak** [comment]
Thanks so much @morazow @jpizagno This is really helping, I have check with our support team and the ports range 20000:21000 were not open and it took them sometime to open it, but now all is open (hopefully :) )
Now the exception has changed:

 java.lang.NoSuchMethodError: com.exasol.jdbc.EXAConnection.EnterParallel(I)I
	at com.exasol.spark.util.ExasolConnectionManager.initParallel(ExasolConnectionManager.scala:55)
	at com.exasol.spark.writer.ExasolWriter.startParallel(ExasolWriter.scala:48)
	at com.exasol.spark.DefaultSource.saveDFTable(DefaultSource.scala:130)
	at com.exasol.spark.DefaultSource.createRelation(DefaultSource.scala:98)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)

I have done the following:

- Added: spark-exasol-connector-assembly-0.2.0.jar under: ~/spark-2.3.2-bin-hadoop2.7/jars/
- Added: --master yarn --deploy-mode client --num-executors=32 to the parameters list in PyCharm Run/Debug Configuration 
- Using Python 3.7
- Using Pyspark 2.3.2
- PyCharm is executing the following to run the script: 
/Test_Spark.py --master yarn --deploy-mode client --num-executors=32
- I'm using the following to write data to exasol table:
employees_dataframe.write \
        .format("exasol") \
        .option("host", "exasolServer") \
        .option("table", "DEV_MO.PAYMENTS22") \
        .option("port", "8563") \
        .option("username", "myuser") \
        .option("password", "mypass") \
        .option("useSSL", "false") \
        .option("create_table", "true") \
        .mode('append') \
        .save()

**Comment by jpizagno** [comment]
@mabdelrazzak 
    I am not sure the project here (spark-exesol-connector) is supporting pycharm. Try using pyspark or spark-submit.

    That message sounds like the jar was not found in: ~/spark-2.3.2-bin-hadoop2.7/jars/.
Check that your environment variable SPARK_HOME is set to ~/spark-2.3.2-bin-hadoop2.7.

I would suggest including the spark-exasol-connector-assembly-0.2.0.jar in the --jars parameter for a pyspark or spark-submit command (like my example above).

To give some technical details, the error ("java.lang.NoSuchMethodError: com.exasol.jdbc.EXAConnection.EnterParallel(I)I") can be caused when the code does not find the JDBC Jar, which is packed in the spark-exasol-connector-assembly-0.2.0.jar. So I think spark-exasol-connector-assembly-0.2.0.jar is not being found.

**Comment by mabdelrazzak** [comment]
Hello @jpizagno 
I can connect to the DB through my script and the table is created successfully but no data is being loaded and I'm still getting the same exception, Exasol cluster has only 2 nodes. I'm getting the same exception in both PyCharm and PySpark terminal.
The jar file "spark-exasol-connector-assembly-0.2.0.jar" is already placed in:
/Library/Java/JavaVirtualMachines/jdk1.8.0_202.jdk/Contents/Home/jre/lib/ext
And
~/spark-2.3.2-bin-hadoop2.7/jars

Am I still missing any jars?

: java.lang.NoSuchMethodError: com.exasol.jdbc.EXAConnection.EnterParallel(I)I
	at com.exasol.spark.util.ExasolConnectionManager.initParallel(ExasolConnectionManager.scala:55)
	at com.exasol.spark.writer.ExasolWriter.startParallel(ExasolWriter.scala:48)
	at com.exasol.spark.DefaultSource.saveDFTable(DefaultSource.scala:130)
	at com.exasol.spark.DefaultSource.createRelation(DefaultSource.scala:98)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)

**Comment by morazow** [comment]
Good morning @mabdelrazzak,

That is strange error. Maybe exasol-jdbc jar not included in assembled connector jar file.

Are you available today (or next week) to do a live session? Then maybe we can go over your PySpark workflow together.

You can reach me on `muhammet.orazov@exasol.com` email.

Best

**Comment by morazow** [comment]
Hello @mabdelrazzak,
Since we were able to solve or recognize the issue, I am going to close this ticket.

Please do not hesitate to open new tickets if you have any questions or issues.
