### ISSUE TITLE
Spark not-nullable column converts to EXASOL column failed while saving

### ISSUE THREAD

**Issue by 3cham** [exasol/spark-exasol-connector#60]
While creating table in EXASOL we infer column information from [spark schema](https://github.com/exasol/spark-exasol-connector/blob/master/src/main/scala/com/exasol/spark/util/Types.scala#L227-L238
). 
Spark says if a column does not contain any null value then this column is not nullable, despite it can contain **empty string**. So our connector will set the column in the EXASOL DDL to NOT NULL. This leads to problem when writing the data to EXASOL if empty strings occur. 

I suggest that we remove this nullable [checking](https://github.com/exasol/spark-exasol-connector/blob/master/src/main/scala/com/exasol/spark/util/Types.scala#L235) for world's peace since it does take a lot of time to find the cause of this problem :)

Let's me know about your opinions @morazow @jpizagno

**Comment by morazow** [comment]
Hey @3cham ,

Good to hear from you! 

Yes, it is a good point! From my side, I would prefer to remove the `NOT NULL` for only string types. But, I guess we can remove it for all types. It puts the validation on the database side, but if users want that, they can filter the dataframe before insert or run `ALTER` command to add that constraint later inside the database. So, it should be safe to remove it from connector. 

Please feel free to send a pull request!
