### ISSUE TITLE
Extend query option with "execute script" command

### ISSUE THREAD

**Issue by MellD** [exasol/spark-exasol-connector#61]
It would be nice to trigger lua scripts also from Spark side. 
If we send a query with "ececute script my.luascript()" we get back the following exception:
"java.sql.SQLException: syntax error, unexpected EXECUTE_"

**Comment by 3cham** [comment]
@MellD I think in this case you can create a view with your query inside EXASOL firstly. The SQL parser inside spark currently does not understand exasol execute syntax.

**Comment by morazow** [comment]
Hello @MellD,

Thank you for the feedback!

Addition to the @3cham comment, spark-exasol-connector is designed to get Spark dataframe from the Exasol table. To do so, it runs `executeQuery` (usually SELECT statements) command and expects [`ResultSet`](https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html) to be returned. 

Unfortunately, you cannot run the `execute script` SQL statements with `executeQuery`. 

But, you should be able to create single JDBC connection to Exasol and run SQL statements from Spark driver (or another cell of notebook) after or before creating the dataframes.

Please refer to the [Exasol JDBC documentation](https://docs.exasol.com/connect_exasol/drivers/jdbc.htm).  The Exasol JDBC driver is already included to the spark-exasol-connector; therefore, you do not have to add it as dependency.

Hope this helps! Please feel free to reach out if you have questions or issues.

**Comment by morazow** [comment]
Hello @MellD,

I am going to close this issue. Please open a new issue if there are more questions.
