### ISSUE TITLE
Receiving "com.exasol.jdbc.ProtocolException: Too long message received" upon attempting to write a large Dataframe into Exasol database

### ISSUE THREAD

**Issue by LordBertson** [exasol/spark-exasol-connector#66]
Hi,

first of all, I am sorry is this is already known or resolved, I have tried to search a bit before posting and haven't found any related posts. 

I am lately encountering an Exception trying to write a large dataframe into an Exasol database:

```
com.exasol.jdbc.ProtocolException: Too long message received
	at com.exasol.jdbc.ExceptionFactory.createSQLException(ExceptionFactory.java:59)
	at com.exasol.jdbc.EXASQLException.getSQLExceptionIntern(EXASQLException.java:50)
	at com.exasol.jdbc.AbstractEXAPreparedStatement.execute(AbstractEXAPreparedStatement.java:216)
	at com.exasol.jdbc.AbstractEXAPreparedStatement.executeUpdate(AbstractEXAPreparedStatement.java:371)
	at com.exasol.jdbc.AbstractEXAPreparedStatement.executeBatch(AbstractEXAPreparedStatement.java:177)
	at com.exasol.spark.writer.ExasolWriter.insertPartition(ExasolWriter.scala:102)
```

The code with which I attempt to write:
```
df.write \
  .format('exasol')
  .options(host=ip,
           port=port_no,
           table=table_name,
           username=username,
           password=pass,
           create_table='true') \
  .mode('overwrite') \
  .save()
```

I am using a Spark 2.4.5 with the Spark Exasol Connector compiled for Scala 2.11, since the one compiled for Scala 2.12 did break on me throwing the `java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object` error, which should be associated with a version mismatch.

I have considered this might be a part of an issue, since according Spark's documentation, Spark 2.4.5 is supposed to be running on Scala 2.12, but I have installed Spark from PyPi as pyspark so I just shrugged and went with what works. What buggers me the most, is that I have managed to write multiple dataframes, some even larger than this one before encountering this issue.

**Comment by LordBertson** [comment]
Okay, got it, it seems to be an unrelated problem that the data contains varchars longer than 2M characters. Sorry.

**Comment by morazow** [comment]
Hey @LordBertson,

Thanks for your feedback! 

We have not hit this issue yet (or reported so far) in the spark-exasol-connector. It is correct that Exasol database has a limit on `VARCHAR` type.

Best
