### ISSUE TITLE
Add package for Java 8

### ISSUE THREAD

**Issue by renardeinside** [exasol/spark-exasol-connector#92]
I've met the following issue using connector v1.0.0 on the latest Databricks Runtimes (7.X, 8.X):
```
Caused by: java.lang.UnsupportedClassVersionError: com/exasol/sql/dql/select/SelectVisitor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
In a nutshell, this means that some dependencies were compiled with Java 11, while in Databricks Runtime we currently support only Java 8. 

Would be great to have some extended version with Java 8 support.

**Comment by morazow** [comment]
Hello @renardeinside,

Thanks for the feedback!

Yes, indeed we compile the connector and Exasol Java libraries with Java 11. We are going to look into it, if we can backport this particular library into Java 8. 

Do you know if there are any plans moving to Java 9+ both Spark and Databricks Runtimes soon?

**Comment by renardeinside** [comment]
> Do you know if there are any plans moving to Java 9+ both Spark and Databricks Runtimes soon?

Unfortunately, I don't have any particular information on this topic. 

What I definitely know is that most used Runtimes with Spark 3.X are on Java 8 (DBR 7.X / DBR 8.X) - that's why I asked for this :)

**Comment by redcatbear** [comment]
Oracle Java 8 is already down to premium support (read: payed support): https://www.oracle.com/java/technologies/java-se-support-roadmap.html

OpenJDK will receive security updates until end of 2025 according to: https://endoflife.date/java

If we support Java 8, we need to provide this as a variant on a second release branch with separate releases, which means double effort. Falling back to Java 8 completely is no option.

**Comment by redcatbear** [comment]
Decision from Product Management: we will support Databricks.

That means we need to start the parallel release branch for Java 8.

**Comment by morazow** [comment]
Hello @renardeinside,

We added support for Java 8 in the latest release. Could you please give it a try?
